version: '3.8'

services:
  postgres:
    image: postgres:15
    container_name: postgres-eps
    environment:
      POSTGRES_USER: eps_admin
      POSTGRES_PASSWORD: admin123
      POSTGRES_DB: eps_db
    ports:
      - "5432:5432"
    volumes:
      - postgres_eps_data:/var/lib/postgresql/data
    restart: always

volumes:
  postgres_eps_data:
